### ISSUE TITLE
Messages with Password

### ISSUE THREAD

**Issue by Jannik-Schroeder** [solun-pm/solun-v2#3]
![237067611-7f71b302-1cea-4cda-ab94-c0b3b167ff92](https://github.com/solun-pm/solun/assets/90240332/d26d8c0a-3ad3-49a2-b2f9-9c02e004ac5d)

Remove Bruteforce Checkbox and add to the Advanced Options Section, also add a Password Field, remember to add password to the model "messages", you can encrypt the password the same way as we encrypt the message, so we don't store it clear in the database, only use the AES_SECRET_KEY Generation Once - secret_key would be for the message & the password.

If the password field is not filled, just leave it blank in the db document, if it's filled it's a string with the encrypted key in the db

**Comment by schroeder-is** [comment]
#4
